CREATE TABLE CONDITIONALACTION_PROCESS
(CONDITIONALACTION_ID BIGINT NOT NULL,
CONDITIONALPROCESSES_KEY BIGINT NOT NULL,
CONDITIONALPROCESSES_ID BIGINT NOT NULL,
PRIMARY KEY (CONDITIONALACTION_ID,CONDITIONALPROCESSES_KEY));
ALTER TABLE CONDITIONALACTION_PROCESS ADD CONSTRAINT FKRSPAGHLD0ECM5SAD0COFDFCWR FOREIGN KEY (CONDITIONALPROCESSES_KEY) REFERENCES STATUS(ID);
ALTER TABLE CONDITIONALACTION_PROCESS ADD CONSTRAINT FK1Q3HYHPEG1DYUJ8YLFGYCXBT9 FOREIGN KEY (CONDITIONALPROCESSES_ID) REFERENCES PROCESS(ID);
ALTER TABLE CONDITIONALACTION_PROCESS ADD CONSTRAINT FKNNBWK2411AM0MU4F3E2DIL3RS FOREIGN KEY (CONDITIONALACTION_ID) REFERENCES CONDITIONALACTION(ID);
