CREATE table EXPORT_ERROR(
ERROR_ID BIGINT, 
MESSAGE_ID BIGINT,
EXPORT_ERROR_TYPE VARCHAR(20) NOT NULL,
CONSTRAINT FK_EXPORT_ERROR_ERROR_ID FOREIGN KEY (ERROR_ID) REFERENCES ERROR(ID),
CONSTRAINT FK_EXPORT_ERROR_MESSAGE_ID FOREIGN KEY (MESSAGE_ID) REFERENCES MESSAGE(ID)
);