CREATE table FIXING_ERROR(
ERROR_ID BIGINT, 
TRANSFER_ID BIGINT,
CONSTRAINT FK_FIXING_ERROR_ERROR_ID FOREIGN KEY (ERROR_ID) REFERENCES ERROR(ID),
CONSTRAINT FK_FIXING_ERROR_TRANSFER_ID FOREIGN KEY (TRANSFER_ID) REFERENCES TRANSFER(ID)
);