CREATE table IMPORT_ERROR(
ERROR_ID BIGINT, 
MESSAGE_ID BIGINT,
IMPORT_ERROR_TYPE VARCHAR(20),
CONSTRAINT FK_IMPORT_ERROR_ERROR_ID FOREIGN KEY (ERROR_ID) REFERENCES ERROR(ID),
CONSTRAINT FK_IMPORT_ERROR_MESSAGE_ID FOREIGN KEY (MESSAGE_ID) REFERENCES MESSAGE(ID)
);