CREATE table INTERFACE_MAPPING_SET(
ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (START WITH 1, INCREMENT BY 1), 
INTERFACE_NAME VARCHAR(50),
MAPPING_TYPE VARCHAR(50) NOT NULL,
IS_INCOMING BOOLEAN NOT NULL,
PROCESSING_ORG_ID BIGINT NOT NULL,
CONSTRAINT UC_INTERFACE_MAPPING_SET UNIQUE (INTERFACE_NAME, MAPPING_TYPE, IS_INCOMING, PROCESSING_ORG_ID),
CONSTRAINT FK_INTERFACE_MAPPING_SET_PROCESSING_ORG_ID FOREIGN KEY (PROCESSING_ORG_ID) REFERENCES LEGAL_ENTITY(ID));