CREATE table MAPPING(
VALUE VARCHAR(50) NOT NULL,
MAPPED_VALUE VARCHAR(50) NOT NULL,
INTERFACE_MAPPING_SET_ID BIGINT NOT NULL,
CONSTRAINT UC_MAPPING UNIQUE (VALUE, INTERFACE_MAPPING_SET_ID),
CONSTRAINT FK_MAPPING_INTERFACE_MAPPING_SET_ID FOREIGN KEY (INTERFACE_MAPPING_SET_ID) REFERENCES INTERFACE_MAPPING_SET(ID));