CREATE table MAPPING(
ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (START WITH 1, INCREMENT BY 1), 
IMPORTER_NAME VARCHAR(50),
MAPPING_TYPE VARCHAR(50) NOT NULL,
VALUE VARCHAR(50) NOT NULL,
MAPPED_VALUE VARCHAR(50) NOT NULL,
CONSTRAINT UC_MAPPING UNIQUE (IMPORTER_NAME, MAPPING_TYPE, VALUE));