CREATE table MESSAGE(
ID          BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (START WITH 1, INCREMENT BY 1),
INCOMING    BOOLEAN NOT NULL,
CREATION_DATE DATE NOT NULL,
LAST_UPDATE_DATE  DATE NOT NULL,
TYPE  VARCHAR(10) NOT NULL,
OBJECT_ID BIGINT,
CONTENT VARCHAR(5000));