CREATE table MESSAGE(
ID          BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (START WITH 1, INCREMENT BY 1),
INCOMING    BOOLEAN NOT NULL,
CREATION_DATE TIMESTAMP NOT NULL,
LAST_UPDATE_DATE  TIMESTAMP NOT NULL,
TYPE  VARCHAR(20) NOT NULL,
INTERFACE_NAME VARCHAR(20) NOT NULL,
OBJECT_ID BIGINT,
OBJECT_TYPE VARCHAR(20),
CONTENT VARCHAR(5000));