CREATE table MESSAGING_LISTENER_FILTER(
LISTENER_ID BIGINT NOT NULL,
FILTER_ID BIGINT NOT NULL,
EXECUTION_ORDER INT NOT NULL,
CONSTRAINT PK_MESSAGING_LISTENER_FILTER PRIMARY KEY (LISTENER_ID, FILTER_ID),
CONSTRAINT FK_MLF_LISTENER_ID FOREIGN KEY (LISTENER_ID) REFERENCES MESSAGING_LISTENER(ID),
CONSTRAINT FK_MLF_FILTER_ID FOREIGN KEY (FILTER_ID) REFERENCES MESSAGING_FILTER(ID));
