CREATE table MESSAGING_EVENT_SUBSCRIPTION(
EVENT_TYPE VARCHAR(100) NOT NULL,
LISTENER_ID BIGINT NOT NULL,
CONSTRAINT PK_MESSAGING_EVENT_SUBSCRIPTION PRIMARY KEY (EVENT_TYPE, LISTENER_ID),
CONSTRAINT FK_MES_LISTENER_ID FOREIGN KEY (LISTENER_ID) REFERENCES MESSAGING_LISTENER(ID));
