CREATE table MESSAGING_LISTENER(
ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NAME VARCHAR(100) UNIQUE NOT NULL,
QUEUE_NAME VARCHAR(100) UNIQUE NOT NULL,
POLLER_DELAY BIGINT NOT NULL DEFAULT 5000,
POLLER_MAX_MESSAGES INT NOT NULL DEFAULT 20,
IS_ENABLED BOOLEAN NOT NULL DEFAULT TRUE);
