CREATE table PRODUCT(
ID          BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY  (START WITH 1, INCREMENT BY 1),
CREATION_TIME  TIMESTAMP NOT NULL,
LAST_UPDATE_TIME  TIMESTAMP NOT NULL,
EXCHANGE_ID BIGINT,
CONSTRAINT FK_EXCHANGE_ID FOREIGN KEY (EXCHANGE_ID) REFERENCES EXCHANGE(ID));