CREATE table RATING_ASSIGNMENT(
ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
RATED_OBJECT_ID BIGINT NOT NULL,
RATED_OBJECT_TYPE VARCHAR(50) NOT NULL,
RATING_ID BIGINT NOT NULL,
VALID_FROM DATE NOT NULL,
VALID_TO DATE,
CONSTRAINT FK_RATING_ASSIGNMENT_RATING_ID FOREIGN KEY (RATING_ID) REFERENCES RATING(ID));
