CREATE table RATING(
ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
CODE VARCHAR(20) NOT NULL,
DESCRIPTION VARCHAR(255),
RATING_AGENCY_ID BIGINT NOT NULL,
CONSTRAINT FK_RATING_RATING_AGENCY_ID FOREIGN KEY (RATING_AGENCY_ID) REFERENCES RATING_AGENCY(ID),
CONSTRAINT UN_RATING_NAME_AGENCY UNIQUE (CODE, RATING_AGENCY_ID));
